name: Hello World

on: [push]

jobs:
    greet:
        runs-on: ubuntu-24.04
        steps:
            - name: Dire bonjour
              run: echo "Hello, Github Actions!"
            - name: Date et heure
              run: date